//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.16 at 09:04:47 AM CET 
//


package cat.eFactures.deliver.pimefactura;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}base64Document"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "base64Document"
})
@XmlRootElement(name = "factura")
public class Factura {

    @XmlElement(required = true)
    protected String base64Document;

    /**
     * Gets the value of the base64Document property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public String getBase64Document() {
        return base64Document;
    }

    /**
     * Sets the value of the base64Document property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setBase64Document(String value) {
        this.base64Document = value;
    }

}
