
package cat.eFactures.deliver.pimefactura.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PimecInvoiceReceptorPortType", targetNamespace = "http://Service.Reception.Invoice.Pimec")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PimecInvoiceReceptorPortType {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:hello")
    @WebResult(targetNamespace = "http://Service.Reception.Invoice.Pimec")
    @RequestWrapper(localName = "hello", targetNamespace = "http://Service.Reception.Invoice.Pimec", className = "cat.eFactures.deliver.pimefactura.ws.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://Service.Reception.Invoice.Pimec", className = "cat.eFactures.deliver.pimefactura.ws.HelloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "http://Service.Reception.Invoice.Pimec")
        String name);

    /**
     * 
     * @param omrequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:summitInvoice")
    @WebResult(targetNamespace = "http://Service.Reception.Invoice.Pimec")
    @RequestWrapper(localName = "summitInvoice", targetNamespace = "http://Service.Reception.Invoice.Pimec", className = "cat.eFactures.deliver.pimefactura.ws.SummitInvoice")
    @ResponseWrapper(localName = "summitInvoiceResponse", targetNamespace = "http://Service.Reception.Invoice.Pimec", className = "cat.eFactures.deliver.pimefactura.ws.SummitInvoiceResponse")
    public String summitInvoice(
        @WebParam(name = "omrequest", targetNamespace = "http://Service.Reception.Invoice.Pimec")
        Object omrequest);

}
