
package cat.eFactures.deliver.pimefactura.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PimecInvoiceReceptor", targetNamespace = "http://Service.Reception.Invoice.Pimec", wsdlLocation = "http://new.pimefactura.com/axis2/services/PimecInvoiceReceptor?wsdl")
public class PimecInvoiceReceptor
    extends Service
{

    private final static URL PIMECINVOICERECEPTOR_WSDL_LOCATION;
    private final static WebServiceException PIMECINVOICERECEPTOR_EXCEPTION;
    private final static QName PIMECINVOICERECEPTOR_QNAME = new QName("http://Service.Reception.Invoice.Pimec", "PimecInvoiceReceptor");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://new.pimefactura.com/axis2/services/PimecInvoiceReceptor?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PIMECINVOICERECEPTOR_WSDL_LOCATION = url;
        PIMECINVOICERECEPTOR_EXCEPTION = e;
    }

    public PimecInvoiceReceptor() {
        super(__getWsdlLocation(), PIMECINVOICERECEPTOR_QNAME);
    }

    public PimecInvoiceReceptor(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns PimecInvoiceReceptorPortType
     */
    @WebEndpoint(name = "PimecInvoiceReceptorHttpSoap11Endpoint")
    public PimecInvoiceReceptorPortType getPimecInvoiceReceptorHttpSoap11Endpoint() {
        return super.getPort(new QName("http://Service.Reception.Invoice.Pimec", "PimecInvoiceReceptorHttpSoap11Endpoint"), PimecInvoiceReceptorPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PimecInvoiceReceptorPortType
     */
    @WebEndpoint(name = "PimecInvoiceReceptorHttpSoap11Endpoint")
    public PimecInvoiceReceptorPortType getPimecInvoiceReceptorHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://Service.Reception.Invoice.Pimec", "PimecInvoiceReceptorHttpSoap11Endpoint"), PimecInvoiceReceptorPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns PimecInvoiceReceptorPortType
     */
    @WebEndpoint(name = "PimecInvoiceReceptorHttpSoap12Endpoint")
    public PimecInvoiceReceptorPortType getPimecInvoiceReceptorHttpSoap12Endpoint() {
        return super.getPort(new QName("http://Service.Reception.Invoice.Pimec", "PimecInvoiceReceptorHttpSoap12Endpoint"), PimecInvoiceReceptorPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PimecInvoiceReceptorPortType
     */
    @WebEndpoint(name = "PimecInvoiceReceptorHttpSoap12Endpoint")
    public PimecInvoiceReceptorPortType getPimecInvoiceReceptorHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://Service.Reception.Invoice.Pimec", "PimecInvoiceReceptorHttpSoap12Endpoint"), PimecInvoiceReceptorPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns PimecInvoiceReceptorPortType
     */
    @WebEndpoint(name = "PimecInvoiceReceptorHttpEndpoint")
    public PimecInvoiceReceptorPortType getPimecInvoiceReceptorHttpEndpoint() {
        return super.getPort(new QName("http://Service.Reception.Invoice.Pimec", "PimecInvoiceReceptorHttpEndpoint"), PimecInvoiceReceptorPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PimecInvoiceReceptorPortType
     */
    @WebEndpoint(name = "PimecInvoiceReceptorHttpEndpoint")
    public PimecInvoiceReceptorPortType getPimecInvoiceReceptorHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://Service.Reception.Invoice.Pimec", "PimecInvoiceReceptorHttpEndpoint"), PimecInvoiceReceptorPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PIMECINVOICERECEPTOR_EXCEPTION!= null) {
            throw PIMECINVOICERECEPTOR_EXCEPTION;
        }
        return PIMECINVOICERECEPTOR_WSDL_LOCATION;
    }

}
